# Generated by Django 5.0.3 on 2024-03-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images'),
        ),
    ]
