# Generated by Django 5.0.3 on 2024-03-14 13:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to=core.models.get_image_upload_path),
        ),
    ]
