# Generated by Django 5.0.3 on 2024-03-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productimages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='This is the <django.db.models.fields.CharField>', null=True),
        ),
    ]
